# Generated by Django 4.2.7 on 2024-03-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0002_alter_passenger_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='nid',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
