# Generated by Django 4.2.7 on 2024-03-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0003_alter_passenger_nid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='balance_after_transaction',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
