# Generated by Django 4.2.7 on 2024-03-03 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0001_initial'),
        ('train', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatnumber',
            name='passenger',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='passenger.passenger'),
        ),
    ]
