# Generated by Django 4.2.7 on 2024-03-05 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0002_seatnumber_passenger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='train_station',
        ),
    ]
