# Generated by Django 4.2.7 on 2024-03-05 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0003_remove_train_train_station'),
        ('seat_booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seatbooking',
            name='is_confirmed',
        ),
        migrations.AlterField(
            model_name='seatbooking',
            name='seat_number',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='train.seatnumber'),
        ),
    ]
